name: clip-finetune-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - pillow
  - json5  # For JSON utilities
  - pickle5
  - faiss-gpu  # GPU version of FAISS
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3  # Match your CUDA version if different
  - deepface
  - pip:
      - transformers
      - datasets
      - ftfy  # sometimes needed for transformers tokenization
      - regex  # used by transformers too
      - git+https://github.com/openai/CLIP.git
      - deepface